# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(500, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(500, 450))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.flameStats = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flameStats.setFont(font)
        self.flameStats.setObjectName("flameStats")
        self.verticalLayout_13.addWidget(self.flameStats)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.strength = QtWidgets.QLabel(self.frame_2)
        self.strength.setObjectName("strength")
        self.verticalLayout_4.addWidget(self.strength)
        self.dexterity = QtWidgets.QLabel(self.frame_2)
        self.dexterity.setObjectName("dexterity")
        self.verticalLayout_4.addWidget(self.dexterity)
        self.intelligence = QtWidgets.QLabel(self.frame_2)
        self.intelligence.setObjectName("intelligence")
        self.verticalLayout_4.addWidget(self.intelligence)
        self.luck = QtWidgets.QLabel(self.frame_2)
        self.luck.setObjectName("luck")
        self.verticalLayout_4.addWidget(self.luck)
        self.allStatPercent = QtWidgets.QLabel(self.frame_2)
        self.allStatPercent.setObjectName("allStatPercent")
        self.verticalLayout_4.addWidget(self.allStatPercent)
        self.attack = QtWidgets.QLabel(self.frame_2)
        self.attack.setObjectName("attack")
        self.verticalLayout_4.addWidget(self.attack)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_5.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_5.addWidget(self.label_22)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem11)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.enterSTR = QtWidgets.QLineEdit(self.frame_2)
        self.enterSTR.setMaxLength(4)
        self.enterSTR.setObjectName("enterSTR")
        self.verticalLayout_9.addWidget(self.enterSTR)
        self.enterDEX = QtWidgets.QLineEdit(self.frame_2)
        self.enterDEX.setMaxLength(4)
        self.enterDEX.setObjectName("enterDEX")
        self.verticalLayout_9.addWidget(self.enterDEX)
        self.enterINT = QtWidgets.QLineEdit(self.frame_2)
        self.enterINT.setMaxLength(4)
        self.enterINT.setObjectName("enterINT")
        self.verticalLayout_9.addWidget(self.enterINT)
        self.enterLUK = QtWidgets.QLineEdit(self.frame_2)
        self.enterLUK.setMaxLength(4)
        self.enterLUK.setObjectName("enterLUK")
        self.verticalLayout_9.addWidget(self.enterLUK)
        self.enterAllStat = QtWidgets.QLineEdit(self.frame_2)
        self.enterAllStat.setMaxLength(1)
        self.enterAllStat.setObjectName("enterAllStat")
        self.verticalLayout_9.addWidget(self.enterAllStat)
        self.enterAttack = QtWidgets.QLineEdit(self.frame_2)
        self.enterAttack.setMaxLength(1)
        self.enterAttack.setObjectName("enterAttack")
        self.verticalLayout_9.addWidget(self.enterAttack)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        spacerItem12 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.flameIcon = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flameIcon.sizePolicy().hasHeightForWidth())
        self.flameIcon.setSizePolicy(sizePolicy)
        self.flameIcon.setMinimumSize(QtCore.QSize(100, 100))
        self.flameIcon.setText("")
        self.flameIcon.setPixmap(QtGui.QPixmap(":/items/eternalFlame.png"))
        self.flameIcon.setScaledContents(True)
        self.flameIcon.setObjectName("flameIcon")
        self.horizontalLayout_5.addWidget(self.flameIcon)
        spacerItem13 = QtWidgets.QSpacerItem(7, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.statEquivalents = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statEquivalents.setFont(font)
        self.statEquivalents.setObjectName("statEquivalents")
        self.verticalLayout_12.addWidget(self.statEquivalents)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.oneMainStat = QtWidgets.QLabel(self.frame)
        self.oneMainStat.setAlignment(QtCore.Qt.AlignCenter)
        self.oneMainStat.setObjectName("oneMainStat")
        self.verticalLayout_3.addWidget(self.oneMainStat)
        self.oneAllStatPercent = QtWidgets.QLabel(self.frame)
        self.oneAllStatPercent.setAlignment(QtCore.Qt.AlignCenter)
        self.oneAllStatPercent.setObjectName("oneAllStatPercent")
        self.verticalLayout_3.addWidget(self.oneAllStatPercent)
        self.oneAttack = QtWidgets.QLabel(self.frame)
        self.oneAttack.setAlignment(QtCore.Qt.AlignCenter)
        self.oneAttack.setObjectName("oneAttack")
        self.verticalLayout_3.addWidget(self.oneAttack)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem16)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem17)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem18)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem19)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.secondaryStatE = QtWidgets.QLineEdit(self.frame)
        self.secondaryStatE.setMaxLength(6)
        self.secondaryStatE.setClearButtonEnabled(False)
        self.secondaryStatE.setObjectName("secondaryStatE")
        self.verticalLayout.addWidget(self.secondaryStatE)
        self.allStatPercentE = QtWidgets.QLineEdit(self.frame)
        self.allStatPercentE.setMaxLength(6)
        self.allStatPercentE.setClearButtonEnabled(False)
        self.allStatPercentE.setObjectName("allStatPercentE")
        self.verticalLayout.addWidget(self.allStatPercentE)
        self.attackE = QtWidgets.QLineEdit(self.frame)
        self.attackE.setMaxLength(6)
        self.attackE.setClearButtonEnabled(False)
        self.attackE.setObjectName("attackE")
        self.verticalLayout.addWidget(self.attackE)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_12.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        spacerItem20 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem20)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem21)
        self.weaponIcon = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weaponIcon.sizePolicy().hasHeightForWidth())
        self.weaponIcon.setSizePolicy(sizePolicy)
        self.weaponIcon.setMinimumSize(QtCore.QSize(100, 100))
        self.weaponIcon.setText("")
        self.weaponIcon.setPixmap(QtGui.QPixmap(":/items/arcaneKnuckle.png"))
        self.weaponIcon.setScaledContents(True)
        self.weaponIcon.setObjectName("weaponIcon")
        self.verticalLayout_15.addWidget(self.weaponIcon)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        spacerItem22 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem22)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem23 = QtWidgets.QSpacerItem(33, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem23)
        self.results = QtWidgets.QTextBrowser(self.frame_3)
        self.results.setObjectName("results")
        self.horizontalLayout_3.addWidget(self.results)
        spacerItem24 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem24)
        self.calculate = QtWidgets.QPushButton(self.frame_3)
        self.calculate.setObjectName("calculate")
        self.horizontalLayout_3.addWidget(self.calculate)
        self.gridLayout.addWidget(self.frame_3, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.calculate, self.secondaryStatE)
        MainWindow.setTabOrder(self.secondaryStatE, self.allStatPercentE)
        MainWindow.setTabOrder(self.allStatPercentE, self.attackE)
        MainWindow.setTabOrder(self.attackE, self.results)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Flame Calculator"))
        self.flameStats.setText(_translate("MainWindow", "Flame Stats"))
        self.strength.setText(_translate("MainWindow", "STR"))
        self.dexterity.setText(_translate("MainWindow", "DEX"))
        self.intelligence.setText(_translate("MainWindow", "INT"))
        self.luck.setText(_translate("MainWindow", "LUK"))
        self.allStatPercent.setText(_translate("MainWindow", "All Stat%"))
        self.attack.setText(_translate("MainWindow", "Attack"))
        self.label_17.setText(_translate("MainWindow", "="))
        self.label_18.setText(_translate("MainWindow", "="))
        self.label_19.setText(_translate("MainWindow", "="))
        self.label_20.setText(_translate("MainWindow", "="))
        self.label_21.setText(_translate("MainWindow", "="))
        self.label_22.setText(_translate("MainWindow", "="))
        self.enterSTR.setPlaceholderText(_translate("MainWindow", "Enter STR"))
        self.enterDEX.setPlaceholderText(_translate("MainWindow", "Enter DEX"))
        self.enterINT.setPlaceholderText(_translate("MainWindow", "Enter INT"))
        self.enterLUK.setPlaceholderText(_translate("MainWindow", "Enter LUK"))
        self.enterAllStat.setPlaceholderText(_translate("MainWindow", "Enter All Stat%"))
        self.enterAttack.setPlaceholderText(_translate("MainWindow", "Enter Attack"))
        self.statEquivalents.setText(_translate("MainWindow", "Stat Equivalents"))
        self.oneMainStat.setText(_translate("MainWindow", "1 Main Stat"))
        self.oneAllStatPercent.setText(_translate("MainWindow", "1% All Stat"))
        self.oneAttack.setText(_translate("MainWindow", "1 Attack"))
        self.label_5.setText(_translate("MainWindow", "="))
        self.label_7.setText(_translate("MainWindow", "="))
        self.label_8.setText(_translate("MainWindow", "="))
        self.secondaryStatE.setPlaceholderText(_translate("MainWindow", "Enter Secondary Stat"))
        self.allStatPercentE.setPlaceholderText(_translate("MainWindow", "Enter Main Stat"))
        self.attackE.setPlaceholderText(_translate("MainWindow", "Enter Main Stat"))
        self.calculate.setText(_translate("MainWindow", "Calculate"))


import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
